# head
menu:
  MENU: /archives
  ABOUT: /about
  # sitemap: /sitemap.xml
  # other menus

rss: /atom.xml
favicon: /favicon.png

date_format: 'MMMM D, YYYY'

google_verification: false  # your token
google_analytics: UA-87613819-1   # your id

livere_id: 'city'
livere_uid: 'MTAyMC8zMjExMS84Njc1'

start_year: 2016

reward_images: # add your qr image
# - type: '微信'
#   url: '/img/wechat.png'
# - type: '支付宝' 
#   url: '/img/wechat.png'
 
